### ISSUE TITLE
Class LaporanK cetak

### ISSUE THREAD

**Issue by imakin** [fnugrahendi/petuk.corp#10]
``` python
Traceback (most recent call last):
  File "/media/kentir1/Development/work/Akunting/petuk.corp/source/kasbank/KasMasuk.py", line 427, in KasBank_KasMasuk_Tambah_Cetak
    self.Laporan_BuktiKasMasuk(kode)
  File "/media/kentir1/Development/work/Akunting/petuk.corp/source/laporan/LaporanK.py", line 299, in Laporan_BuktiKasMasuk
    total = total +  int(result[x][4])
ValueError: invalid literal for int() with base 10: 'ALhamdullillah Bisa'
```

kro field (4) ning database e bukane catatan kan? atau mending nganggo fungsi koyo ngene wae nek njupuk field sing umum (nek nganggo select \* seko 1 tabel) `self.KasBank_DetailKasMasuk_Field.index("nilaiDetail")` kui return field nilaiDetail ning tabel nomor piro... atau cek class KasBank ning KasBankK.py

makasih kro

**Comment by iqrok** [comment]
neng nggonku no 4 he..
![capture](https://cloud.githubusercontent.com/assets/7772479/6657047/bd676480-cb71-11e4-8ca3-b702a7ff04fb.PNG)
dela tek ganti

**Comment by iqrok** [comment]
Sory2 salahku..
sing liyane ana ra index sing beda? 
ben komputer bisa beda2 index field e?

**Comment by imakin** [comment]
ho o yo padakke wae kro,, nek meh nggolek otomatis nomor field e iso nganggo information_schema

``` python
result = self.DatabaseRunQuery("SELECT `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA`='"+self.dbDatabase+"' AND `TABLE_NAME`='gd_detail_kas_masuk';")
self.KasBank_DetailKasMasuk_Field = list(itertools.chain.from_iterable(result))
```

kui `self.KasBank_DetailKasMasuk_Field` isine **list**, tinggal `self.KasBank_DetailKasMasuk_Field.index("nilaiDetail")` metu field nilaiDetail ki ning kolom nomer piro...
nek nganggo join tinggal tambahi banyak field sing di join kiwo ne `self.KasBank_DetailKasMasuk_Field.index("nilaiDetail")+0`
